name: Release Deployment

on:
  release:
    types: [published]

env:
  BUILD_TYPE: Release
  LD_LIBRARY_PATH: /usr/lib/llvm-9/lib
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build-graphics:
    name: 'Build and Release'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          architecture: x64

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_branch

      - name: Output branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'

      - name: Use cmake
        run: cmake --version

      - name: Add LLVM gpg key
        run: wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: Add LLVM toolchain to sources.list.d
        run: echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' | sudo tee -a /etc/apt/sources.list.d/llvm.list

      - name: Add ubuntu toolchain ppa
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test

      - name: Update the package cache
        run: sudo apt-get update

      - name: Install required packages
        run: sudo apt-get install gnupg2 mingw-w64 autoconf-archive llvm-9 llvm-9-dev clang-9 gcc-7 g++-7 gcc-multilib g++-multilib libssl1.0-dev

      - name: Add clang-9 path to /usr/local/bin
        run: sudo ln -s /usr/bin/clang-9 /usr/local/bin/clang && sudo ln -s /usr/bin/clang++-9 /usr/local/bin/clang++

      - name: Install third-party dependencies
        run: scripts/install-deps-bin.sh

      - name: Import GPG key
        run: ./.github/scripts/import-gpg.sh

      - name: Build Project (Java + Native)
        run: mvn install -P'release' -Drevision=${{ steps.extract_branch.outputs.branch }} -Dcompile.native=true -Dgraphics.target=native-build-cc-all -Dinput.target=native-build-cc-all -Dbuild.type=${BUILD_TYPE} -Dlicense.skipUpdateLicense=true -DskipTests=true -B -V --settings ./.github/scripts/settings.xml

      - name: Deploy to Sonatype Staging
        run: mvn deploy -P'deploy-sonatype,release' -Drevision=${{ steps.extract_branch.outputs.branch }} -Dmaven.antrun.skip=true -DskipTests=true -Dlicense.skipUpdateLicense=true --settings ./.github/scripts/settings.xml

      #- name: Deploy to Github
      #  run: mvn deploy -P'deploy-github,release' -Drevision=${{ steps.extract_branch.outputs.branch }} -Dmaven.wagon.http.pool=false -Dmaven.antrun.skip=true -DskipTests=true -Dlicense.skipUpdateLicense=true --settings ./.github/scripts/settings.xml
